name: openapi_client_builder
description: Build openapi clients from the OpenApi specification.
version: 0.0.1
# homepage: https://www.example.com

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  openapi_schema_builder:
    path: ../openapi_schema_builder
  build: any
  dio: any

dev_dependencies:
  build_config: any
  build_runner: any
  pedantic: any
  test: any
